import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en" className="scrollbar-hide">
      <body>
        <Navbar />
        <div className="min-h-dvh pt-14">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
